name: fitpet_adventure
description: ""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  fl_chart: ^0.70.2
  go_router: ^14.8.1
  pedometer: ^4.0.2
  permission_handler: ^11.4.0
  percent_indicator: ^4.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dependency_validator: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/pet.png
    # By https://mts1944.itch.io/christmas-hat
    - assets/hat.png
    # By https://xxashuraxx.itch.io/sword
    - assets/sword.png
    - assets/testaccount.json
