name: fitpet_adventure
description: ""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  fl_chart: ^0.70.2
  go_router: ^14.8.1
  pedometer: ^4.0.2
  permission_handler: ^11.4.0
  percent_indicator: ^4.2.4
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dependency_validator: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    # Pets
    - assets/earth_egg.png
    - assets/earth_baby.png
    - assets/earth_old.png
    - assets/sky_egg.png
    - assets/sky_baby.png
    - assets/sky_old.png
    - assets/cosmicnightskyegg.png
    - assets/floralfantasycreatureegg.png
    - assets/nightskycloudsegg.png
    - assets/underwaterkelpforestegg.png
    - assets/space_egg.png
    - assets/space_baby.png
    - assets/space_old.png
    - assets/water_egg.png
    - assets/water_baby.png
    - assets/water_old.png
    - assets/egg_pic.png
    - assets/group_pic.png
    - assets/signup.png
    - assets/signup2.png

    # Cosmetics
    # By https://xxashuraxx.itch.io/sword
    - assets/sword.png

    # By https://snoopethduckduck.itch.io/shields
    - assets/shield.png

    # By https://snoopethduckduck.itch.io/swords
    - assets/staff.png

    # By https://free-game-assets.itch.io/free-bow-and-crossbow-pixel-art-icons
    - assets/bow.png
    - assets/crossbow.png

    # By https://tankepxs.itch.io/free-weapon-pack
    - assets/m1911.png
    - assets/mac10.png

    # By https://henrysoftware.itch.io/pixel-food
    - assets/beer.png
    - assets/moonshine.png
    - assets/whiskey.png
    - assets/wine.png