// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cbL4IBz6q9bEtq_mzi5L7zltOe4h2js',
    appId: '1:546624203315:web:5e585a4674d5317176d146',
    messagingSenderId: '546624203315',
    projectId: 'fitpetadventure-4ce43',
    authDomain: 'fitpetadventure-4ce43.firebaseapp.com',
    databaseURL: 'https://fitpetadventure-4ce43-default-rtdb.firebaseio.com',
    storageBucket: 'fitpetadventure-4ce43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB72wT4KXbGHVQUTn_ZLuXF5tGKuAoUww',
    appId: '1:546624203315:android:042a59e8b0db366d76d146',
    messagingSenderId: '546624203315',
    projectId: 'fitpetadventure-4ce43',
    databaseURL: 'https://fitpetadventure-4ce43-default-rtdb.firebaseio.com',
    storageBucket: 'fitpetadventure-4ce43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm5LK1hOyTEhizMYG3Y5fGJPn8R2VGoyM',
    appId: '1:546624203315:ios:53354bf8ffe47a3176d146',
    messagingSenderId: '546624203315',
    projectId: 'fitpetadventure-4ce43',
    databaseURL: 'https://fitpetadventure-4ce43-default-rtdb.firebaseio.com',
    storageBucket: 'fitpetadventure-4ce43.firebasestorage.app',
    iosClientId: '546624203315-rkpmhp92u1qbane8bdvbjdlf7eue7cfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitpetAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm5LK1hOyTEhizMYG3Y5fGJPn8R2VGoyM',
    appId: '1:546624203315:ios:53354bf8ffe47a3176d146',
    messagingSenderId: '546624203315',
    projectId: 'fitpetadventure-4ce43',
    databaseURL: 'https://fitpetadventure-4ce43-default-rtdb.firebaseio.com',
    storageBucket: 'fitpetadventure-4ce43.firebasestorage.app',
    iosClientId: '546624203315-rkpmhp92u1qbane8bdvbjdlf7eue7cfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitpetAdventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4cbL4IBz6q9bEtq_mzi5L7zltOe4h2js',
    appId: '1:546624203315:web:599f6adea57ce85f76d146',
    messagingSenderId: '546624203315',
    projectId: 'fitpetadventure-4ce43',
    authDomain: 'fitpetadventure-4ce43.firebaseapp.com',
    databaseURL: 'https://fitpetadventure-4ce43-default-rtdb.firebaseio.com',
    storageBucket: 'fitpetadventure-4ce43.firebasestorage.app',
  );

}